/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ru.rgs.openshift.test;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-07-06")
public class THeaders implements org.apache.thrift.TBase<THeaders, THeaders._Fields>, java.io.Serializable, Cloneable, Comparable<THeaders> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("THeaders");

  private static final org.apache.thrift.protocol.TField CORRELATIONID_FIELD_DESC = new org.apache.thrift.protocol.TField("correlationid", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new THeadersStandardSchemeFactory());
    schemes.put(TupleScheme.class, new THeadersTupleSchemeFactory());
  }

  private String correlationid; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CORRELATIONID((short)1, "correlationid");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CORRELATIONID
          return CORRELATIONID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CORRELATIONID, new org.apache.thrift.meta_data.FieldMetaData("correlationid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(THeaders.class, metaDataMap);
  }

  public THeaders() {
  }

  public THeaders(
    String correlationid)
  {
    this();
    this.correlationid = correlationid;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public THeaders(THeaders other) {
    if (other.isSetCorrelationid()) {
      this.correlationid = other.correlationid;
    }
  }

  public THeaders deepCopy() {
    return new THeaders(this);
  }

  @Override
  public void clear() {
    this.correlationid = null;
  }

  public String getCorrelationid() {
    return this.correlationid;
  }

  public THeaders setCorrelationid(String correlationid) {
    this.correlationid = correlationid;
    return this;
  }

  public void unsetCorrelationid() {
    this.correlationid = null;
  }

  /** Returns true if field correlationid is set (has been assigned a value) and false otherwise */
  public boolean isSetCorrelationid() {
    return this.correlationid != null;
  }

  public void setCorrelationidIsSet(boolean value) {
    if (!value) {
      this.correlationid = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CORRELATIONID:
      if (value == null) {
        unsetCorrelationid();
      } else {
        setCorrelationid((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CORRELATIONID:
      return getCorrelationid();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CORRELATIONID:
      return isSetCorrelationid();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof THeaders)
      return this.equals((THeaders)that);
    return false;
  }

  public boolean equals(THeaders that) {
    if (that == null)
      return false;

    boolean this_present_correlationid = true && this.isSetCorrelationid();
    boolean that_present_correlationid = true && that.isSetCorrelationid();
    if (this_present_correlationid || that_present_correlationid) {
      if (!(this_present_correlationid && that_present_correlationid))
        return false;
      if (!this.correlationid.equals(that.correlationid))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_correlationid = true && (isSetCorrelationid());
    list.add(present_correlationid);
    if (present_correlationid)
      list.add(correlationid);

    return list.hashCode();
  }

  @Override
  public int compareTo(THeaders other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCorrelationid()).compareTo(other.isSetCorrelationid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCorrelationid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.correlationid, other.correlationid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("THeaders(");
    boolean first = true;

    sb.append("correlationid:");
    if (this.correlationid == null) {
      sb.append("null");
    } else {
      sb.append(this.correlationid);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (correlationid == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'correlationid' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class THeadersStandardSchemeFactory implements SchemeFactory {
    public THeadersStandardScheme getScheme() {
      return new THeadersStandardScheme();
    }
  }

  private static class THeadersStandardScheme extends StandardScheme<THeaders> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, THeaders struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CORRELATIONID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.correlationid = iprot.readString();
              struct.setCorrelationidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, THeaders struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.correlationid != null) {
        oprot.writeFieldBegin(CORRELATIONID_FIELD_DESC);
        oprot.writeString(struct.correlationid);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class THeadersTupleSchemeFactory implements SchemeFactory {
    public THeadersTupleScheme getScheme() {
      return new THeadersTupleScheme();
    }
  }

  private static class THeadersTupleScheme extends TupleScheme<THeaders> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, THeaders struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.correlationid);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, THeaders struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.correlationid = iprot.readString();
      struct.setCorrelationidIsSet(true);
    }
  }

}

